### ISSUE TITLE
copy should be replaced with ConstantTimeCopy?

### ISSUE THREAD

**Issue by Inkeliz** [aead/chacha20poly1305#2]
I'm looking to use the `XChaCha20Poly1305`, but the official library for Golang doesn't supports it. I take a time looking the code and it brings me a question. I don't know if here is the right place for that, but I will ask here because I don't find a better room for that.

The `crypto/subtle` have a function `ConstantTimeCopy`, but I don't find any library using it. Only the [`PKCS1v15`](https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go#L125-L127).

In the ChaCha20Poly1305, [in this line](https://github.com/aead/chacha20poly1305/blob/master/chacha20poly1305.go#L38) have a simple `copy`,  copying the `key`. If the `ConstantTimeCopy` is used will have some benefit? If not, where should the `ConstantTimeCopy` be used?

**Comment by aead** [comment]
If you look at the documentation of `ConstantTimeCopy`:
>ConstantTimeCopy copies the contents of y into x (a slice of equal length) if v == 1. If v == 0, x is left unchanged. Its behavior is undefined if v takes any other value. 

`ConstantTimeCopy` does a conditional copy. It only copies `y` into `x` if the `v == 1`. So `ConstantTimeCopy` is only useful if you want to copy only under a certain condition - similar to a constant-time *conditional* swap operation. The referenced line always copies the key - so it does not make sense to use a conditional copy implementation. A non-conditional copy is not an issue - even if it's not constant time (as long as the time does not depend of the copied content :wink: )

`ConstantTimeCopy` is useful if you want to do a copy operation based on a condition of secret data - a naive example: copy some content if the first bit of the secret key is `0`.
